default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: nline
  password: n.Line202

development:
  <<: *default
  database: task_app_development

test:
  <<: *default
  database: task_app_test

production:
  <<: *default
  database: task_app_production
  username: nline
  password: n.Line202
